// Sample data for authors
const authors = [
  {
    name: "John Smith",
    university: "MIT",
    dob: "1980-05-15",
    hIndex: 42,
    gender: "Male",
  },
  {
    name: "Emily Johnson",
    university: "Stanford",
    dob: "1975-08-22",
    hIndex: 37,
    gender: "Female",
  },
  {
    name: "Michael Brown",
    university: "Harvard",
    dob: "1985-03-10",
    hIndex: 29,
    gender: "Male",
  },
  {
    name: "Sarah Davis",
    university: "Caltech",
    dob: "1978-11-05",
    hIndex: 35,
    gender: "Female",
  },
  {
    name: "David Wilson",
    university: "Oxford",
    dob: "1972-07-19",
    hIndex: 51,
    gender: "Male",
  },
  {
    name: "Jennifer Lee",
    university: "Cambridge",
    dob: "1982-09-30",
    hIndex: 31,
    gender: "Female",
  },
  {
    name: "Robert Taylor",
    university: "ETH Zurich",
    dob: "1970-12-25",
    hIndex: 48,
    gender: "Male",
  },
  {
    name: "Lisa Anderson",
    university: "UCLA",
    dob: "1988-04-12",
    hIndex: 25,
    gender: "Female",
  },
  {
    name: "James Martin",
    university: "Imperial College",
    dob: "1983-06-18",
    hIndex: 33,
    gender: "Male",
  },
  {
    name: "Patricia White",
    university: "UC Berkeley",
    dob: "1976-02-28",
    hIndex: 39,
    gender: "Female",
  },
  {
    name: "Daniel Clark",
    university: "University of Tokyo",
    dob: "1981-10-14",
    hIndex: 28,
    gender: "Male",
  },
  {
    name: "Elizabeth Lewis",
    university: "EPFL",
    dob: "1979-07-23",
    hIndex: 36,
    gender: "Female",
  },
  {
    name: "Thomas Walker",
    university: "UCL",
    dob: "1974-01-09",
    hIndex: 44,
    gender: "Male",
  },
  {
    name: "Nancy Hall",
    university: "University of Toronto",
    dob: "1984-08-07",
    hIndex: 27,
    gender: "Female",
  },
  {
    name: "Charles Allen",
    university: "National University of Singapore",
    dob: "1977-11-16",
    hIndex: 32,
    gender: "Male",
  },
];

// Sample data for research papers
const researchPapers = [
  {
    title: "Advancements in Quantum Computing",
    conference: "QIP 2023",
    date: "2023-01-15",
    authorId: 1,
  },
  {
    title: "Machine Learning in Healthcare",
    conference: "NeurIPS 2022",
    date: "2022-12-10",
    authorId: 2,
  },
  {
    title: "The Future of Renewable Energy",
    conference: "Nature Energy",
    date: "2023-02-20",
    authorId: 3,
  },
  {
    title: "Blockchain Technology and Security",
    conference: "IEEE S&P 2023",
    date: "2023-03-05",
    authorId: 4,
  },
  {
    title: "Neural Networks for Image Recognition",
    conference: "CVPR 2023",
    date: "2023-06-15",
    authorId: 5,
  },
  {
    title: "Climate Change Modeling",
    conference: "Nature Climate",
    date: "2023-01-30",
    authorId: 6,
  },
  {
    title: "Cybersecurity in IoT",
    conference: "USENIX Security 2023",
    date: "2023-04-12",
    authorId: 7,
  },
  {
    title: "Artificial General Intelligence",
    conference: "ICML 2023",
    date: "2023-07-22",
    authorId: 8,
  },
  {
    title: "Sustainable Urban Development",
    conference: "Nature Cities",
    date: "2023-02-28",
    authorId: 9,
  },
  {
    title: "Quantum Cryptography",
    conference: "CRYPTO 2023",
    date: "2023-08-10",
    authorId: 10,
  },
  {
    title: "Deep Learning for Drug Discovery",
    conference: "Nature Medicine",
    date: "2023-03-15",
    authorId: 11,
  },
  {
    title: "Autonomous Vehicles",
    conference: "ICRA 2023",
    date: "2023-05-20",
    authorId: 12,
  },
  {
    title: "Natural Language Processing",
    conference: "ACL 2023",
    date: "2023-07-30",
    authorId: 13,
  },
  {
    title: "Robotics in Manufacturing",
    conference: "IROS 2023",
    date: "2023-09-12",
    authorId: 12,
  },
  {
    title: "Augmented Reality Applications",
    conference: "UIST 2023",
    date: "2023-10-05",
    authorId: 15,
  },
  {
    title: "Edge Computing",
    conference: "MobiCom 2023",
    date: "2023-04-25",
    authorId: 1,
  },
  {
    title: "5G Network Security",
    conference: "NDSS 2023",
    date: "2023-06-30",
    authorId: 2,
  },
  {
    title: "Biomedical Engineering",
    conference: "Nature Biomedical",
    date: "2023-03-10",
    authorId: 3,
  },
  {
    title: "Computer Vision in Agriculture",
    conference: "CVPR 2023",
    date: "2023-06-20",
    authorId: 4,
  },
  {
    title: "AI Ethics and Bias",
    conference: "FAT* 2023",
    date: "2023-01-20",
    authorId: 5,
  },
  {
    title: "Renewable Energy Storage",
    conference: "Nature Energy",
    date: "2023-02-15",
    authorId: 6,
  },
  {
    title: "Distributed Systems",
    conference: "SOSP 2023",
    date: "2023-10-15",
    authorId: 7,
  },
  {
    title: "Human-Computer Interaction",
    conference: "CHI 2023",
    date: "2023-04-30",
    authorId: 8,
  },
  {
    title: "Data Privacy",
    conference: "PETS 2023",
    date: "2023-05-10",
    authorId: 9,
  },
  {
    title: "Computational Biology",
    conference: "RECOMB 2023",
    date: "2023-07-05",
    authorId: 10,
  },
  {
    title: "Autonomous Drones",
    conference: "ICRA 2023",
    date: "2023-05-25",
    authorId: 11,
  },
  {
    title: "Natural Language Generation",
    conference: "EMNLP 2023",
    date: "2023-11-10",
    authorId: 12,
  },
  {
    title: "Robotic Process Automation",
    conference: "ICAPS 2023",
    date: "2023-08-20",
    authorId: 13,
  },
  {
    title: "Extended Reality in Education",
    conference: "CHI 2023",
    date: "2023-04-15",
    authorId: 12,
  },
  {
    title: "Federated Learning",
    conference: "ICLR 2023",
    date: "2023-09-25",
    authorId: 15,
  },
];

module.exports = { authors, researchPapers };
