import pkg from "pg";
const { Client } = pkg;

const defaultClient = new Client({
  user: "hyfuser",
  host: "localhost",
  database: "postgres",
  password: "hyfpassword",
  port: 5432,
});

async function setupDatabase() {
  let client;
  try {
    await defaultClient.connect();

    await defaultClient.query(`DROP DATABASE IF EXISTS meetup;`);
    await defaultClient.query(`CREATE DATABASE meetup;`);
    console.log('Database "meetup" created.');

    await defaultClient.end();

    client = new Client({
      user: "hyfuser",
      host: "localhost",
      database: "meetup",
      password: "hyfpassword",
      port: 5432,
    });
    await client.connect();

    await client.query(`
      CREATE TABLE Invitee (
        invitee_no INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        invitee_name VARCHAR(100),
        invited_by VARCHAR(100)
      );
    `);

    await client.query(`
      CREATE TABLE Room (
        room_no INT PRIMARY KEY,
        room_name VARCHAR(64),
        floor_number SMALLINT
      );
    `);

    await client.query(`
      CREATE TABLE Meeting (
        meeting_no INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        meeting_title VARCHAR(64),
        starting_time TIMESTAMP,
        ending_time TIMESTAMP,
        room_no INT REFERENCES Room(room_no)
      );
    `);

    console.log("Tables created.");

    await client.query(`
  INSERT INTO Invitee (invitee_name, invited_by) VALUES
    ('Alice Johnson', 'Bob Smith'),
    ('Bob Smith', 'Carol White'),
    ('Carol White', 'David Lee'),
    ('David Lee', 'Alice Johnson'),
    ('Eve Brown', 'Bob Smith');
`);

    await client.query(`
      INSERT INTO Room (room_name, floor_number) VALUES
  ('Blue Room', 1),
  ('Green Room', 1),
  ('Yellow Room', 2),
  ('Red Room', 2),
  ('Conference Hall', 3);
    `);

    await client.query(`
  INSERT INTO Meeting (meeting_title, starting_time, ending_time, room_no) VALUES
  ('Project Kickoff', '2025-09-01 09:00:00', '2025-09-01 10:00:00', 1),
  ('Design Review', '2025-09-02 11:00:00', '2025-09-02 12:30:00', 2),
  ('Team Standup', '2025-09-03 09:30:00', '2025-09-03 10:00:00', 3),
  ('Client Presentation', '2025-09-04 14:00:00', '2025-09-04 15:30:00', 4),
  ('Retrospective', '2025-09-05 16:00:00', '2025-09-05 17:00:00', 5);
`);

    console.log("Sample data inserted.");
  } catch (err) {
    console.error("Error:", err);
  } finally {
    if (client) await client.end().catch(() => {});
    await defaultClient.end().catch(() => {});
    console.log("Setup complete (connections closed).");
  }
}

setupDatabase();
